version: '3'

services:
  php:
    container_name: lemp_php_jameinw
    build: php/
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    ports:
      - "9000"
    depends_on:
      - db

  nginx:
    container_name: lemp_nginx_jameinw
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html

      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    environment:
      VIRTUAL_HOST: ${NGINX_HOST}
      LETSENCRYPT_HOST: ${NGINX_LETSENCRYPT}

    expose:
      - "80"

    networks:
      - webproxy
      - default
      
  db:
    container_name: lemp_mariadb_jameinw
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/

    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101

  pma:
    container_name: lemp_phpmyadmin_jameinw
    image: phpmyadmin/phpmyadmin
    restart: always

    networks:
      - webproxy
      - default

    environment:
      VIRTUAL_HOST: ${ADMINER_HOST}
      LETSENCRYPT_HOST: ${ADMINER_LETSENCRYPT}

    expose:
      - "80"

networks:
  default:
    external:
      name:
        web_network_jameinw
  webproxy:
    external:
      name: webproxy_xops
